### ISSUE TITLE
C_USE_ITEM def is outdated

### ISSUE THREAD

**Issue by Brazuca87** [tera-proxy/tera-data#24]
C_USE_ITEM uses a counter as the first 4 bytes, and then another set of 4 bytes before it starts with the current def of gameId

**Comment by pinkipi** [comment]
The current definition is correct. Starting with patch 92, certain packets (listed in `integrity/(major-patch-version).json`) have an additional integrity check as part of their header, making the header 12 bytes long instead of 4. I've updated the readme to reflect this.

**Comment by Brazuca87** [comment]
@pinkipi how would that be handled in a mod? or there is nothing to do about those?

When a mod is sending those, it just sends a (seemingly) random number for counter and I suppose checksum?

**Comment by pinkipi** [comment]
Proxy re-calculates integrity check after all hooks have finished. The only thing that matters when serializing those packets is that there is space reserved for the header, hence it is filled with unallocated memory until then. There's no way to send the wrong value from a mod, so you don't have to worry about it unless you're writing defs.

**Comment by Brazuca87** [comment]
I guess that's where I am running into issues... If I'm writting defs, how would I handle this?

**Comment by pinkipi** [comment]
Just look up whether the packet in question has integrity check, and if it does then treat the header (the part not included in def) as 12 bytes long instead of 4.
